# Generated by Django 5.0.6 on 2024-05-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_karyalay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karyalay_name_marathi', models.CharField(max_length=500)),
                ('karyalay_name_eglish', models.CharField(max_length=500)),
                ('nearby_location_marathi', models.CharField(max_length=500)),
                ('nearby_location_eglish', models.CharField(max_length=500)),
                ('address_marathi', models.CharField(max_length=500)),
                ('address_eglish', models.CharField(max_length=500)),
                ('owner_name', models.CharField(max_length=500)),
                ('mobile', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
