# Generated by Django 5.0.6 on 2024-05-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_karyalay',
            name='pin_code',
            field=models.IntegerField(null=True),
        ),
    ]
