# Generated by Django 5.0.6 on 2024-05-12 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0002_add_karyalay_pin_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_karyalay',
            new_name='Karyalay',
        ),
    ]
