# Generated by Django 5.0.6 on 2024-05-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('event_date', models.DateField()),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
