# Generated by Django 5.0.6 on 2024-05-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
        ('sunil', '0005_alter_karyalay_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='karyalay',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.karyalay'),
        ),
    ]
