# Generated by Django 5.0.6 on 2024-05-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_remove_event_booked_date'),
        ('sunil', '0005_alter_karyalay_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('image_2', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('image_3', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('image_4', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('image_5', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('karyalay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.karyalay')),
            ],
        ),
    ]
