# Generated by Django 5.0.6 on 2024-05-15 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_images'),
        ('sunil', '0005_alter_karyalay_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_code', models.CharField(max_length=500)),
                ('karyalay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.karyalay')),
            ],
        ),
    ]
