# Generated by Django 5.0.6 on 2024-09-06 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_map'),
        ('sunil', '0007_karyalay_jeson_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lucky_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('lucky_day', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.IntegerField()),
                ('karyalay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.karyalay')),
            ],
        ),
    ]
