# Generated by Django 5.0.6 on 2024-05-25 03:06

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sunil', '0005_alter_karyalay_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='You_Tube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_1', embed_video.fields.EmbedVideoField()),
                ('url_2', embed_video.fields.EmbedVideoField()),
                ('karyalay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.karyalay')),
            ],
        ),
    ]
